### ISSUE TITLE
erstell mal ne requirements.txt

### ISSUE THREAD

**Issue by DAMcraft** [FunProgramer/IServAppWindows#1]
btw hab ich und mein kumpel auhc an einer app gearbeitet, better-iserv.tk

**Comment by FunProgramer** [comment]
Hi @DAMcraft,
ich habe dieses Repository fast vergessen. Habe aber in der Zwischenzeit viel an der App gearbeitet. Die Änderungen habe ich jetzt auch in dieses Repository übernommen. Eine Requirement.txt ist jetzt auch dabei.

**Comment by FunProgramer** [comment]
Ich habe mir jetzt auch mal deine App angesehen. Ich finde, sie ist von der Benutzeroberfläche um einiges besser als meine. Mich stört nur das man bei jedem Neustart seinen Benutzernamen und sein Passwort eingeben muss. Wollen wir zusammen arbeiten?

**Comment by DAMcraft** [comment]
ja daran arbeiten wir grade, an einem besseren login system, ich muss mal nachfragen ob das geht

**Comment by FunProgramer** [comment]
ok

**Comment by DAMcraft** [comment]
keine ahnung beim straten bekomm ich nen error dass ich dbus installieren muss kenn mich aber nicht mit python aus, bekomme bei der installation nen error
`Collecting dbus-python                                                                                                    Using cached dbus-python-1.2.16.tar.gz (576 kB)                                                                       Using legacy 'setup.py install' for dbus-python, since package 'wheel' is not installed.                                Installing collected packages: dbus-python                                                                                  Running setup.py install for dbus-python ... error                                                                      ERROR: Command errored out with exit status 1:                                                                           command: 'c:\users\damia\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\damia\\AppData\\Local\\Temp\\pip-install-6jc4ri_v\\dbus-python_d92e2e10fd574e3897233fc2cfba1ce7\\setup.py'"'"'; __file__='"'"'C:\\Users\\damia\\AppData\\Local\\Temp\\pip-install-6jc4ri_v\\dbus-python_d92e2e10fd574e3897233fc2cfba1ce7\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\damia\AppData\Local\Temp\pip-record-kvl0lojh\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\damia\appdata\local\programs\python\python37-32\Include\dbus-python'                                                   cwd: C:\Users\damia\AppData\Local\Temp\pip-install-6jc4ri_v\dbus-python_d92e2e10fd574e3897233fc2cfba1ce7\          Complete output (5 lines):                                                                                              running install                                                                                                         running build                                                                                                           creating C:\Users\damia\AppData\Local\Temp\pip-install-6jc4ri_v\dbus-python_d92e2e10fd574e3897233fc2cfba1ce7\build      creating C:\Users\damia\AppData\Local\Temp\pip-install-6jc4ri_v\dbus-python_d92e2e10fd574e3897233fc2cfba1ce7\build\temp.win32-3.7                                                                                                               error: [WinError 193] %1 ist keine zulässige Win32-Anwendung                                                            ----------------------------------------                                                                            ERROR: Command errored out with exit status 1: 'c:\users\damia\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\damia\\AppData\\Local\\Temp\\pip-install-6jc4ri_v\\dbus-python_d92e2e10fd574e3897233fc2cfba1ce7\\setup.py'"'"'; __file__='"'"'C:\\Users\\damia\\AppData\\Local\\Temp\\pip-install-6jc4ri_v\\dbus-python_d92e2e10fd574e3897233fc2cfba1ce7\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\damia\AppData\Local\Temp\pip-record-kvl0lojh\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\damia\appdata\local\programs\python\python37-32\Include\dbus-python' Check the logs for full command output.`

Screenshot: https://i.imgur.com/8VsDFPC.png

**Comment by FunProgramer** [comment]
Lösche nochmal alles und clone dir dann das Repository erneut

**Comment by FunProgramer** [comment]
Da ist dann auch eine requirements.txt dabei

**Comment by DAMcraft** [comment]
ja klappt war im falschen ordner, noch im alten
